import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import {
    Card,
    CardHeader,
    CardBody,
    Stack,
    StackDivider,
    Heading,
    CardFooter,
  } from "@chakra-ui/react";
const Detail = (props)=>{
    return (
        <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${styles.main}`}>
        <Card w={"100%"} overflow={"hidden"}>
          <CardHeader display={"flex"} justifyContent={{base:'center', sm:'start'}}>
            <Heading as={"h1"} size="xl">
              Detail
            </Heading>
          </CardHeader>

          <CardBody id="content">
            <Stack divider={<StackDivider />} spacing="6">
                
              
            </Stack>
          </CardBody>

          <CardFooter display={'flex'} justifyContent={'center'} alignItems={'Center'}>

          </CardFooter>
        </Card>
        </main>
        </>
    )
}

// lanjutkan detail
export default Detail