import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import CardList from "./component/Card-list";
import CreateNote from "./component/CreateNote";
import {
  Card,
  CardHeader,
  CardBody,
  Stack,
  Heading,
  StackDivider,
  CardFooter,
} from "@chakra-ui/react";
import Database from "../utils/db";
import { InferGetServerSidePropsType } from "next";

const inter = Inter({ subsets: ["latin"] });

/**
 * The Home component renders a list of CardList components based on the data provided, or displays a
 * message if the data is empty.
 * @returns The `Home` component is returning a JSX structure that includes a `Head` component with
 * meta tags and a title, a `main` element with a `Card` component containing a header with a heading
 * "My Notepad" and a body with a stack of `CardList` components or a heading "Catatan Masih Kosong" if
 * `data` is empty.
 */
const Home = ({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  let temp_html = [];
  if (data.length != 0) {
    for (const item of data) {
      temp_html.push(
        <CardList
          key={item.id}
          id={item.id}
          title={item.title}
          description={item.content}
          createdAt={item.createdAt}
        ></CardList>
      );
    }
  } else {
    temp_html.push(
      <Heading as="h2" size={"xl"} color={'gray.300'} textAlign={'center'}>
        Catatan Masih Kosong
      </Heading>
    );
  }
  return (
    <>
      <Head>
        <title>My Notepad</title>
        <meta name="description" content="Generated by My Notepad" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {/* template card */}
        <Card w={"100%"} overflow={"hidden"}>
          <CardHeader display={"flex"} justifyContent={{base:'center', sm:'start'}}>
            <Heading as={"h1"} size="xl">
              My Notepad
            </Heading>
          </CardHeader>

          <CardBody id="content">
            <Stack divider={<StackDivider />} spacing="6">
              {temp_html}
            </Stack>
          </CardBody>

          <CardFooter display={'flex'} justifyContent={'center'} alignItems={'Center'}>
            <CreateNote>
              
            </CreateNote>
          </CardFooter>
        </Card>

      </main>
    </>
  );
};

export default Home;

/**
 * This function retrieves data from a database, formats the creation date of each entry according to
 * Indonesian locale, and returns the data as props.
 * @returns The `getServerSideProps` function is returning an object with a `props` key containing the
 * `data` array after formatting the `createdAt` field of each element in the array to a localized date
 * and time format for the "Asia/Jakarta" timezone.
 */
export async function getServerSideProps() {
  const data = await Database.note.findMany();
  const timeZone = "Asia/Jakarta";
  for (let index = 0; index < data.length; index++) {
    const element = data[index];
    const formattedDate = new Intl.DateTimeFormat("id-ID", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      timeZone,
    }).format(element.createdAt);

    element.createdAt = formattedDate.replace("pukul", "");
  }
  return {
    props: { data },
  };
}
